### PR TITLE
add my name

### PR DESCRIPTION
**Pull request by SuperCoder7979**
i think that should work

### CODE REVIEW

**Comment by SuperCoder7979** [comment]
nevermind

**Comment by OvermindDL1** [comment]
Eh, it's easier to type than adding `@` anyway.  ^.^

**Comment by OvermindDL1** [comment]
For note, that won't compile (the bot will complain soon) because it is missing an `R` for Regex.  ;-)

**Comment by OvermindDL1** [comment]
And replace `@SuperCoder79` with `SuperCoder79`

**Pull request merged**
